### ISSUE TITLE
Syntax suggestion improvement

### ISSUE THREAD

**Issue by Joe23232** [huonw/cfor#5]
Hi, currently we have to type this:

```rust
#[macro_use] extern crate cfor;

fn main() {
    cfor!{let mut x = 1; x < 0x1000; x *= 2; {
        println!("power of 2: {}", x);
    }}
}
```

But to make it closer to c-style for loop, wouldn't this be better:

```rust
#[macro_use] extern crate cfor;

fn main() {
    cfor! let mut x = 1; x < 0x1000; x *= 2; {
        println!("power of 2: {}", x);
    }
}
```

**Comment by huonw** [comment]
Thanks for the suggestion, and for waiting for a response. I don't think your proposal works with current Rust: a macro needs to be followed by delimiters like `()`, `[]` or `{}`.

**Comment by Raj2032** [comment]
I see thanks
